// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Data;

#nullable disable

namespace Recipes.Migrations
{
    [DbContext(typeof(RecipeCatalogContext))]
    [Migration("20250222185219_Ingr")]
    partial class Ingr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeIngredientId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            Quantity = 500m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3,
                            Quantity = 800m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 8,
                            Quantity = 1m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 7,
                            Quantity = 3m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 9,
                            Quantity = 20m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 2,
                            Quantity = 800m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 1,
                            Quantity = 400m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 8,
                            Quantity = 1m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            Quantity = 2m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 9,
                            Quantity = 10m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 12,
                            Quantity = 2m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 10,
                            Quantity = 4m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 5,
                            Quantity = 2m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 4,
                            Quantity = 1m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 6,
                            Quantity = 100m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 11,
                            Quantity = 300m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 1,
                            Quantity = 300m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 4,
                            Quantity = 6m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 7,
                            Quantity = 2m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 8,
                            Quantity = 1m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 5,
                            Quantity = 2m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 13,
                            Quantity = 200m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 7,
                            Quantity = 5m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 4,
                            Quantity = 5m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 10,
                            Quantity = 6m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 7,
                            Quantity = 3m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 1,
                            Quantity = 600m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 8,
                            Quantity = 1m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 4,
                            Quantity = 2m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 7,
                            Quantity = 2m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 11,
                            Quantity = 400m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 1,
                            Quantity = 350m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 9,
                            Quantity = 20m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 6,
                            Quantity = 200m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 12,
                            Quantity = 2m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 14,
                            Quantity = 200m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 16,
                            Quantity = 1m,
                            RecipeIngredientId = 0
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 15,
                            Quantity = 10m,
                            RecipeIngredientId = 0
                        });
                });

            modelBuilder.Entity("Recipes.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Предястие"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Основно"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Десерт"
                        });
                });

            modelBuilder.Entity("Recipes.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Месо"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Картофи"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Зеле"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Чушки"
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "Краставици"
                        },
                        new
                        {
                            IngredientId = 6,
                            Name = "Сирене"
                        },
                        new
                        {
                            IngredientId = 7,
                            Name = "Чесън"
                        },
                        new
                        {
                            IngredientId = 8,
                            Name = "Лук"
                        },
                        new
                        {
                            IngredientId = 9,
                            Name = "Магданоз"
                        },
                        new
                        {
                            IngredientId = 10,
                            Name = "Домати"
                        },
                        new
                        {
                            IngredientId = 11,
                            Name = "Ориз"
                        },
                        new
                        {
                            IngredientId = 12,
                            Name = "Яйца"
                        },
                        new
                        {
                            IngredientId = 13,
                            Name = "Кисело мляко"
                        },
                        new
                        {
                            IngredientId = 14,
                            Name = "Брашно"
                        },
                        new
                        {
                            IngredientId = 15,
                            Name = "Захар"
                        },
                        new
                        {
                            IngredientId = 16,
                            Name = "Тиква"
                        },
                        new
                        {
                            IngredientId = 17,
                            Name = "Сол"
                        },
                        new
                        {
                            IngredientId = 18,
                            Name = "Пипер"
                        });
                });

            modelBuilder.Entity("Recipes.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CookingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CategoryId = 2,
                            CookingTime = "4-5 часа",
                            Description = "Традиционно ястие с месо и кисело зеле.",
                            ImagePath = "/images/kapama.jpg",
                            Instructions = "1. Нарежете киселото зеле на ситно и го наредете в голяма тенджера...",
                            Title = "Капама"
                        },
                        new
                        {
                            RecipeId = 2,
                            CategoryId = 2,
                            CookingTime = "1 час",
                            Description = "Ястие с картофи, кайма и подправки.",
                            ImagePath = "/images/musaka.jpg",
                            Instructions = "1. Нарежете картофите на кубчета и ги запържете...",
                            Title = "Мусака"
                        },
                        new
                        {
                            RecipeId = 3,
                            CategoryId = 1,
                            CookingTime = "10-15 минути",
                            Description = "Класическа салата с домати, краставици и сирене.",
                            ImagePath = "/images/salata.jpg",
                            Instructions = "1. Нарежете доматите, краставиците и чушките...",
                            Title = "Шопска салата"
                        },
                        new
                        {
                            RecipeId = 4,
                            CategoryId = 2,
                            CookingTime = "1-2 часа",
                            Description = "Чушки, пълнени с ориз, месо и подправки.",
                            ImagePath = "/images/pulneni.jpg",
                            Instructions = "1. Запържете лука и добавете месото...",
                            Title = "Пълнени чушки"
                        },
                        new
                        {
                            RecipeId = 5,
                            CategoryId = 1,
                            CookingTime = "10 минути",
                            Description = "Традиционна студена супа от краставици и кисело мляко.",
                            ImagePath = "/images/tarator.jpg",
                            Instructions = "1. Нарежете краставиците и ги смесете с кисело мляко...",
                            Title = "Таратор"
                        },
                        new
                        {
                            RecipeId = 6,
                            CategoryId = 3,
                            CookingTime = "3-4 часа",
                            Description = "Разядка от печени чушки и домати.",
                            ImagePath = "/images/l.jpg",
                            Instructions = "1. Опечете чушките и ги обелете...",
                            Title = "Лютеница"
                        },
                        new
                        {
                            RecipeId = 7,
                            CategoryId = 2,
                            CookingTime = "1-2 часа",
                            Description = "Месо, лук и чушки, задушени в тенджера.",
                            ImagePath = "/images/kavurma.jpg",
                            Instructions = "1. Нарежете месото и го запържете...",
                            Title = "Кавърма"
                        },
                        new
                        {
                            RecipeId = 8,
                            CategoryId = 2,
                            CookingTime = "2-3 часа",
                            Description = "Зелеви листа с ориз и месо.",
                            ImagePath = "/images/sarmi.jpg",
                            Instructions = "1. Измийте лозовите или зелева листа...",
                            Title = "Сарми"
                        },
                        new
                        {
                            RecipeId = 9,
                            CategoryId = 3,
                            CookingTime = "1-2 часа",
                            Description = "Печено тестено изделие със сирене.",
                            ImagePath = "/images/banica.jpg",
                            Instructions = "1. Разбийте яйцата и смесете с натрошеното сирене...",
                            Title = "Баница"
                        },
                        new
                        {
                            RecipeId = 10,
                            CategoryId = 3,
                            CookingTime = "1 час",
                            Description = "Печена тиква с подправки.",
                            ImagePath = "/images/tikva.jpg",
                            Instructions = "1. Нарежете тиквата и я запечете във фурната...",
                            Title = "Печена тиква"
                        });
                });

            modelBuilder.Entity("RecipeIngredient", b =>
                {
                    b.HasOne("Recipes.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Recipes.Models.Recipe", b =>
                {
                    b.HasOne("Recipes.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Recipes.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Recipes.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Recipes.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
